{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: user-db-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore #
  target:
    name: user-db-secret
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: {{ .Values.secrets.secretPath }}
        property: DB_HOST
    - secretKey: DB_USER
      remoteRef:
        key: {{ .Values.secrets.secretPath }}
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.secrets.secretPath }}
        property: DB_PASSWORD
    - secretKey: DB_NAME
      remoteRef:
        key: {{ .Values.secrets.secretPath }}
        property: DB_NAME

{{- end }}