{{- if .Values.localDb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-mysql
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-mysql
  template:
    metadata:
      labels:
        app: user-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootpassword
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: user-mysql
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: user-mysql
  ports:
    - port: 3306
      targetPort: 3306
{{- end }}