{{- if .Values.localDb.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-schema
  namespace: {{ .Values.namespace }}
data:
  schema.sql: |
{{ .Files.Get "schema.sql" | indent 4 }}
{{- end }}