apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-sa
  namespace: {{ .Values.namespace }}
  {{- if .Values.aws.enabled }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.irsa.roleArn }}
  {{- end }}